### ISSUE TITLE
Laptops with 1920x1080

### ISSUE THREAD

**Issue by dawidd4** [spitfirex86/Ray2Fix#3]
I tested Ray2Fix 1.2.1 on 3 different devices, on the GOG Version without GOG Galaxy (C:/Gog Games/Rayman 2).
1) Laptop with a Ryzen 4600H + GTX 1650,
2) Laptop with Intel HD Graphics,
3) PC with RTX 2070 Super (← 1920x1200 monitor for the PC).

The game ran on any laptop in 1680×1050 with black borders. On a 60 Hz monitor there were only 30 Hz and 59 Hz modes available.
The game runs with no issues on the PC in 1920x1200. But during the loading screen, however, that one with all characters on a narrow stripe, there was a 1px flickering frame around the screen.

...
But testing Rayman 2 without Ray2Fix, I was able to play in 1920x1080 on these laptops. In DirectX mode, set in the nGlide_config.exe
I tested the game on a fourth device, a laptop with an old Athlon A8-6410 from 2014, with integrated AMD graphics. With the DirectX the game was lagging sometimes. I didn't test Ray2Fix on it.

**Comment by spitfirex86** [comment]
I'm not exactly sure what's the issue here?
The black borders are intentional, Rayman 2 is locked to the 4:3 aspect ratio. You can manually set the resolution to 1920x1080 if you really want, but the game will be stretched horizontally:
![image](https://user-images.githubusercontent.com/33195187/131511072-2b0fdedc-fa90-419c-ab2a-92ad50efbebb.png)
![image](https://user-images.githubusercontent.com/33195187/131511095-b3ffce1a-c1da-419e-84e2-c3d60c39af9e.png)

**Comment by icup321** [comment]
I just had the same issue, turns out if you set Scaling Mode to "Centered" on dgVoodoo it only lets you run it up to 1680x1050 for some reason. If you set it back to "Unspecified" (which is the default setting) it should fix it.

**Comment by spitfirex86** [comment]
Fixed in 1.3.0.
